packages:
  - apps/user-interface/*
  - apps/api/*
  - apps/ai/*
  - apps/workers/*
  - libs/shared/*
  - libs/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - aws-sdk
  - better-sqlite3
  - core-js
  - core-js-pure
  - cypress
  - dtrace-provider
  - nx
  - protobufjs
  - re2
