# ---------------------------------- Cluster -----------------------------------
cluster.name: HelixAI

# ------------------------------------ Node ------------------------------------
node.name: helix-elasticsearch
# assign exactly the roles you need (master+data+ingest on a single‑node)
node.roles: [ master, data, ingest ]

# ----------------------------------- Network ----------------------------------
network.host: 0.0.0.0
http.port: 9200
# new name for the transport port
transport.port: 9300

# -------------------------- Bootstrap / Discovery -----------------------------
# On a single‑node cluster you can just remove discovery entirely.
# If you ever scale to multiple masters, use cluster.initial_master_nodes once
#cluster.initial_master_nodes: [ "helix-elasticsearch" ]

# --------------------------------- Memory Lock -------------------------------
bootstrap.memory_lock: true

# ---------------------------------- Scripting --------------------------------
# if you really need inline, but inline is disabled by default in 8.x
script.allowed_types: inline
