services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    restart: always
    networks:
      - helix
    ports:
      - '2181:2181'     # host:container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-1
    restart: always
    networks:
      - helix
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Define both internal (for inter-broker) and external (for clients) listeners:
      KAFKA_LISTENERS: |
        INTERNAL://0.0.0.0:29092,
        EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: |
        INTERNAL://kafka-1:29092,
        EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

  kafka-2:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-2
    restart: always
    networks:
      - helix
    depends_on:
      - zookeeper
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: |
        INTERNAL://0.0.0.0:29093,
        EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: |
        INTERNAL://kafka-2:29093,
        EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

  kafka-3:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-3
    restart: always
    networks:
      - helix
    depends_on:
      - zookeeper
    ports:
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: |
        INTERNAL://0.0.0.0:29094,
        EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: |
        INTERNAL://kafka-3:29094,
        EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

networks:
  helix:
    driver: bridge
