name: Label Synchronization

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    paths:
      - '.github/labels.yaml' # Only triggers when labels.yaml is changed
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

jobs:
  sync-labels:
    name: Sync Labels # Clearer job name
    runs-on: self-hosted # Runs on a self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4 # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4 # Ensure Node.js is set up, required by many GitHub Actions
        with:
          node-version: '16' # Set a specific Node.js version for consistency

      - name: Cache Node.js Modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.npm # Caches the npm dependencies
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # Cache key based on OS and package-lock.json
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Sync Labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2
        with:
          config-file: .github/labels.yaml # Path to the labels configuration file
          delete-other-labels: true # Removes labels not defined in the config file

      - name: Post-run cleanup
        if: failure()
        run: |
          echo "Cleanup actions if the label sync fails"
          # Add any cleanup steps here if needed
