name: Create Pull Request

on:
  # Schedule to run daily at 2am
  schedule:
    - cron: '0 2 * * *'

  # Trigger the workflow on push to the specified branches
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
      - 'release/*'

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 9.7.1

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g commitlint

      - name: Validate commit messages with commitlint
        run: |
          git log --format=%B $(git rev-parse HEAD)~1..HEAD | commitlint
        continue-on-error: true # Allows the workflow to continue even if commitlint fails

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }} # Use the current branch
          base: develop # Assuming you want to merge into develop
          title: '🤖⚙️ Automated PR: Update from ${{ github.ref_name }} ⚙️🤖' # Use emojis to make it fun! 🚀
          body: 'This is an automated PR created for the branch ${{ github.ref_name }}.'
          labels: 'automated, dependencies'

      - name: Notify if commitlint failed
        if: failure() && steps.create_pr.outcome == 'skipped'
        run: echo "Commitlint failed or PR already exists, skipping PR creation."
